extends SceneTree
const Main=preload("res://scripts/main.gd")
var passed:=0
var failed:=0
func check(condition: bool,name: String) -> void:
	if condition: passed+=1;print("PASS ",name)
	else:failed+=1;print("FAIL ",name)
func key(code: Key) -> InputEventKey:
	var event:=InputEventKey.new();event.physical_keycode=code;event.pressed=true;return event
func _initialize() -> void: call_deferred("run")
func run() -> void:
	var game=Main.new();root.add_child(game);game.set_process(false)
	game.mode="title";game.save_exists=false
	game.choose_menu(1)
	check(game.mode=="dialog" and game.dialog_return=="title","title help keeps return destination")
	game._unhandled_input(key(KEY_ESCAPE))
	check(game.mode=="title","closing help returns to title without starting game")
	game.start_game(false)
	check(game.mode=="play" and game.save_exists,"new journey starts and saves")
	game._unhandled_input(key(KEY_ESCAPE))
	check(game.mode=="pause","Escape pauses play")
	game.choose_menu(1);game._unhandled_input(key(KEY_SPACE))
	check(game.mode=="pause","pause help returns to pause")
	game.choose_menu(2)
	check(game.core.assisted,"assist setting changes and saves")
	game.choose_menu(3)
	check(game.reduced_motion,"reduced motion toggles")
	game.choose_menu(0)
	check(game.mode=="play","resume returns to game")
	game._unhandled_input(key(KEY_M));check(game.mode=="map","map opens")
	game._unhandled_input(key(KEY_M));check(game.mode=="play","map closes repeatedly without navigation loss")
	game._notification(Main.NOTIFICATION_APPLICATION_FOCUS_OUT)
	check(game.mode=="pause","losing application focus pauses")
	game.choose_menu(4)
	check(game.mode=="title" and game.save_exists,"return to title retains saved journey")
	game.choose_menu(1)
	check(game.confirm_new,"new game with save asks before replacing")
	game.choose_menu(1)
	check(not game.confirm_new and game.mode=="title","cancel new game preserves title and progress")
	game.start_game(true)
	check(game.mode=="play" and game.core.assisted,"continue restores saved settings and progress")
	game.core.flags.double_jump=true;game.core.sparks=77;game.write_save()
	var saved:Dictionary=JSON.parse_string(FileAccess.get_file_as_string(Main.SAVE))
	check(saved.flags.double_jump and saved.sparks==77,"atomic save persists gameplay state")
	check(FileAccess.file_exists(Main.SAVE+".backup"),"save keeps previous backup")
	game.pending={"attack_press":true};game.mode="play";game._unhandled_input(key(KEY_M))
	check(game.pending.is_empty(),"opening map clears pending action")
	game.mode="play";game.core.events=[{"type":"dialog","title":"Test","text":"Test"}];game.consume_events();game._unhandled_input(key(KEY_ENTER))
	check(game.mode=="play","world dialogue dismisses to play")
	game.mode="title";game.confirm_new=false;var f:=FileAccess.open(Main.SAVE,FileAccess.WRITE);f.store_string("{not-json}");f.close();game.start_game(true)
	check(game.mode=="title" and game.toast_time>0,"corrupt continue shows recovery message without overwriting")
	game.write_save()
	var origin:=Vector2(100,140);var size:=Vector2(80,80)
	check(game.actor_rect(origin,size,-1).position==origin and game.actor_rect(origin,size,-1).size.x==-80,"left-facing texture flips in place without moving its world anchor")
	game.core.enter_room("boss",Vector2(590,388));var floor_camera:Vector2=game.camera_target();game.core.player.pos.y=205
	check(game.camera_target().y==floor_camera.y and 412-game.camera_target().y<290,"boss ground telegraphs remain inside frame during high jumps")
	print("UI_RESULT ",passed," passed; ",failed," failed")
	game.queue_free();quit(1 if failed else 0)
